### PR TITLE
Price modifiers

### PR DESCRIPTION
**Pull request by hoffmabc**
Ready for review. Hopefully this worked since I cherry picked the commits from the widget work.

### CODE REVIEW

**Comment by morebrownies** [comment]
Hey @hoffmabc I'm trying to submit change to this PR and I'm running into permission issues with GH.  It's asking to reconfirm my 2fa but it's not working at the moment.

In the meantime, while I try to figure that out, here's the handful of changes I was trying to submit. It may be quicker for you to layer them in on your end.

Other than these few changes, it's looking great. 

screenshot 2018-08-13 12 43 10


screenshot 2018-08-13 12 43 33



screenshot 2018-08-13 12 43 17

screenshot 2018-08-13 12 43 24

screenshot 2018-08-13 12 43 38

**Comment by hoffmabc** [comment]
ok i can push these out

**Comment by morebrownies** [comment]
great, thanks

**Comment by hoffmabc** [comment]
Ok changes pushed in @morebrownies.

**Pull request merged**
